import { PivotViewComponent } from '@syncfusion/ej2-react-pivotview';
import { DataManager, UrlAdaptor } from '@syncfusion/ej2-data';
import './App.css';

function App() {
  let pivotObj: PivotViewComponent;

  let oData: DataManager = new DataManager({
    url: 'https://localhost:7284/api/Pivot',
    insertUrl: 'https://localhost:7284/api/Pivot/Insert',
    updateUrl: 'https://localhost:7284/api/Pivot/Update',
    removeUrl: 'https://localhost:7284/api/Pivot/Remove',
    adaptor: new UrlAdaptor
  });
  
  const dataSourceSettings = {
    dataSource: oData,
    expandAll: true,
    rows: [{ name: 'shipCity' }],
    columns: [{ name: 'customerID' }],
    values: [{ name: 'freight' }],
    filters: [],
  }
  const editSettings = { allowEditing: true, allowAdding: true, allowDeleting: true, mode: 'Normal' };
  
  function beginDrillThrough(args: any) {
    for (var i = 0; i < args.gridObj.columns.length; i++) {
      if (args.gridObj.columns[i].field == "orderID") {
        // Enable isPrimaryKey property for the primary key column
        // This field is used to uniquely identify records for CRUD operations (Insert, Update, Delete)
        // Primary keys are required for Update and Delete operations to target the correct record
        args.gridObj.columns[i].isPrimaryKey = true;
      } else {
        // Show all non-primary key columns in the drill-through dialog for editing
        // Only columns defined in the data source will appear in the grid
        // Primary keys are typically auto-generated by the database and should not be user-editable
        args.gridObj.columns[i].visible = true;
      }
    }
  }
  return (<PivotViewComponent id='PivotView' ref={(scope: any) => { pivotObj = scope; }} height={350} dataSourceSettings={dataSourceSettings} editSettings={editSettings} load={load} beginDrillThrough={beginDrillThrough}></PivotViewComponent>);
};

export default App;